backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "src/posts/img" # Media files will be stored in the repo under images/uploads
public_folder: "./img"
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Category", name: "category", widget: "string", default: "upcoming"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: list, default: ['term_1', 'term_2']}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "media" # Used in routes, e.g., /admin/collections/blog
    label: "Media" # Used in the UI
    folder: "src/posts/media" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Category", name: "category", widget: "string", default: "upcoming"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "YouTube link", name: "youtubelink", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "thumbnail", widget: "hidden", default: "./mediadefault.jpg"}
